apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-retain
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  fileSystemId: # efs fileSystem Id 입력
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"

