apiVersion: v1
kind: Pod
metadata:
  name: asm-secret-reader
  namespace: nestjs-boilerplate-config-variable
spec:
  serviceAccountName: asm-reader-dev
  containers:
    - name: secret-reader
      image: amazonlinux:2
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 3600; done"]
