apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: rancher-monitoring-gateway
  namespace: cattle-monitoring-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName:
      hosts:
        -