apiVersion: v1
kind: Pod
metadata:
  name: loki-grafana
spec:
  securityContext:
    fsGroup: 472
  containers:
  - name: grafana
    image: grafana/grafana:8.3.5
    securityContext:
      runAsUser: 0

