grafana:
  enabled: true
  persistence:
    enabled: true
    existingClaim: grafana-pvc
  securityContext:
    fsGroup: 472
    runAsGroup: 472
    runAsUser: 472
  initChownData:
    enabled: false

loki:
  enabled: true
  persistence:
    enabled: true
    existingClaim: loki-pvc

